export const data=[
    {
       name: "Hindi"  ,
       value: "di " 
    },
    {
        name:"Abkhazian",
        value:"ab"
    }
    ,
    {
       name:"Arabic",
       value:"ar"
    }
    ,
    {
        name:"Arabic (AE)",
        value:"ar-ae"
     },
     {
        name:"Assamese",
        value:"as"
     },
     {
        name:"Bihari languages",
        value:"bh"
     },
     {
        name:"Bengali",
        value:"bn"
     },
     {
        name:"Bulgarian",
        value:"bg"
     },
     {
        name:"Belarusian",
        value:"be"
     },
     {
        name:"Chinese",
        value:"zh-CN"
     }, 
     {
        name:"Dutch",
        value:"nl"
     }, 
     {
        name:"English",
        value:"en"
     },
      {
        name:"English (UK)",
        value:"en-gb"
     },
     {
        name:"English (NZ) ",
        value:"en-nz"
     },
     {
        name:"English (US)",
        value:"en-us"
     },
     {
        name:"French",
        value:"fr"
     },
     {
        name:"Filipino",
        value:"fil"
     },
     {
        name:"German",
        value:"de"
     },
     {
        name:"Gujarati",
        value:"gu"
     },
     {
        name:"Hindi",
        value:"hi"
     },
     {
        name:"Indonesian",
        value:"id"
     },
     {
        name:"Irish",
        value:"ga"
     },
     {
        name:"Italian",
        value:"it"
     },
     {
        name:"Japanese",
        value:"ja"
     },
     {
        name:"Kashmiri",
        value:"ks"
     }
     ,
     {
      name:"Kannada",
      value:"kn"
     },
     {
        name:"Korean",
        value:"ko"
       },
       {
        name:"Malayalam",
        value:"ml"
       },
       {
        name:"Marath",
        value:"mr"
       },
       {
        name:"Mongolian",
        value:"mn"
       },
       {
        name:"Nepali",
        value:"ne"
       },
       {
        name:"Oriya",
        value:"or"
       },
       {
        name:"Panjabi; Punjabi",
        value:"pa"
       },
       {
        name:"Persian",
        value:"fa"
       },
       {
        name:"Russian",
        value:"ru"
       },{
        name:"Sanskrit",
        value:"sa"
       },{
        name:"Santali",
        value:"sat"
       },{
        name:"Serbian",
        value:"sr"
       },{
        name:"Tamil",
        value:"ta"
       },{
        name:"Telugu",
        value:"te"
       },{
        name:"Turkish",
        value:"tr"
       },{
        name:"Ukrainian",
        value:"uk"
       },{
        name:"Urdu",
        value:"ur"
       }
]